# OSSAA Schools Seed Script
# Run with: rails runner db/seeds/ossaa_schools.rb

puts "🏫 Seeding OSSAA Schools..."

# Create OSSAA Account
ossaa_account = Account.find_or_create_by(name: "OSSAA") do |account|
  puts "  📋 Creating OSSAA account..."
end

# Create OSSAA School Classes
school_classes_data = [
  { name: "6A", ordinal: 5 },
  { name: "5A", ordinal: 4 },
  { name: "4A", ordinal: 3 },
  { name: "3A", ordinal: 2 },
  { name: "2A", ordinal: 1 }
]

school_classes = {}
school_classes_data.each do |class_data|
  school_class = SchoolClass.find_or_create_by(
    name: class_data[:name],
    account: ossaa_account
  ) do |sc|
    sc.ordinal = class_data[:ordinal]
    puts "  📚 Creating school class #{class_data[:name]}..."
  end
  school_classes[class_data[:name]] = school_class
end

# OSSAA Schools Data
ossaa_schools_data = [
  # 6A Schools
  { name: "Bartlesville", class: "6A" },
  { name: "Bixby", class: "6A" },
  { name: "Broken Arrow", class: "6A" },
  { name: "Capitol Hill", class: "6A" },
  { name: "Choctaw", class: "6A" },
  { name: "Deer Creek (Edmond)", class: "6A" },
  { name: "Edmond Memorial", class: "6A" },
  { name: "Edmond North", class: "6A" },
  { name: "Edmond Santa Fe", class: "6A" },
  { name: "Eisenhower", class: "6A" },
  { name: "Enid", class: "6A" },
  { name: "Jenks", class: "6A" },
  { name: "Moore", class: "6A" },
  { name: "Muskogee", class: "6A" },
  { name: "Mustang", class: "6A" },
  { name: "Norman", class: "6A" },
  { name: "Norman North", class: "6A" },
  { name: "Northwest Classen", class: "6A" },
  { name: "Owasso", class: "6A" },
  { name: "Piedmont", class: "6A" },
  { name: "Ponca City", class: "6A" },
  { name: "Putnam City", class: "6A" },
  { name: "Putnam City North", class: "6A" },
  { name: "Putnam City West", class: "6A" },
  { name: "Sand Springs", class: "6A" },
  { name: "Sapulpa", class: "6A" },
  { name: "Southmoore", class: "6A" },
  { name: "Stillwater", class: "6A" },
  { name: "U. S. Grant", class: "6A" },
  { name: "Union", class: "6A" },
  { name: "Westmoore", class: "6A" },
  { name: "Yukon", class: "6A" },

  # 5A Schools
  { name: "Altus", class: "5A" },
  { name: "Bishop Kelley", class: "5A" },
  { name: "Booker T Washington", class: "5A" },
  { name: "Carl Albert", class: "5A" },
  { name: "Claremore", class: "5A" },
  { name: "Classen SAS at NE", class: "5A" },
  { name: "Collinsville", class: "5A" },
  { name: "Coweta", class: "5A" },
  { name: "Del City", class: "5A" },
  { name: "Duncan", class: "5A" },
  { name: "Durant", class: "5A" },
  { name: "East Central", class: "5A" },
  { name: "Edison Prep", class: "5A" },
  { name: "El Reno", class: "5A" },
  { name: "Elgin", class: "5A" },
  { name: "Guthrie", class: "5A" },
  { name: "Guymon", class: "5A" },
  { name: "John Marshall", class: "5A" },
  { name: "Lawton", class: "5A" },
  { name: "MacArthur", class: "5A" },
  { name: "McAlester", class: "5A" },
  { name: "Memorial (Tulsa)", class: "5A" },
  { name: "Midwest City", class: "5A" },
  { name: "Nathan Hale", class: "5A" },
  { name: "Noble", class: "5A" },
  { name: "Pryor", class: "5A" },
  { name: "Santa Fe South", class: "5A" },
  { name: "Shawnee", class: "5A" },
  { name: "Southeast", class: "5A" },
  { name: "Tahlequah", class: "5A" },
  { name: "Western Heights", class: "5A" },
  { name: "Will Rogers", class: "5A" },

  # 4A Schools
  { name: "Ada", class: "4A" },
  { name: "Anadarko", class: "4A" },
  { name: "Ardmore", class: "4A" },
  { name: "ASTEC", class: "4A" },
  { name: "Berryhill", class: "4A" },
  { name: "Bethany", class: "4A" },
  { name: "Bishop McGuinness", class: "4A" },
  { name: "Blanchard", class: "4A" },
  { name: "Bridge Creek", class: "4A" },
  { name: "Bristow", class: "4A" },
  { name: "Broken Bow", class: "4A" },
  { name: "Byng", class: "4A" },
  { name: "Cache", class: "4A" },
  { name: "Catoosa", class: "4A" },
  { name: "Checotah", class: "4A" },
  { name: "Chickasha", class: "4A" },
  { name: "Cleveland", class: "4A" },
  { name: "Clinton", class: "4A" },
  { name: "Cushing", class: "4A" },
  { name: "Douglass", class: "4A" },
  { name: "Dove Science (OKC)", class: "4A" },
  { name: "Elk City", class: "4A" },
  { name: "Eufaula", class: "4A" },
  { name: "Ft. Gibson", class: "4A" },
  { name: "Glenpool", class: "4A" },
  { name: "Grove", class: "4A" },
  { name: "Harding Charter Prep", class: "4A" },
  { name: "Harding Fine Arts Academy", class: "4A" },
  { name: "Harrah", class: "4A" },
  { name: "Hilldale", class: "4A" },
  { name: "Idabel", class: "4A" },
  { name: "Inola", class: "4A" },
  { name: "Jay", class: "4A" },
  { name: "Kingfisher", class: "4A" },
  { name: "Locust Grove", class: "4A" },
  { name: "Lone Grove", class: "4A" },
  { name: "Madill", class: "4A" },
  { name: "Mannford", class: "4A" },
  { name: "McLain", class: "4A" },
  { name: "McLoud", class: "4A" },
  { name: "Miami", class: "4A" },
  { name: "Mount St. Mary", class: "4A" },
  { name: "Muldrow", class: "4A" },
  { name: "Newcastle", class: "4A" },
  { name: "North Rock Creek", class: "4A" },
  { name: "Oologah-Talala", class: "4A" },
  { name: "Pauls Valley", class: "4A" },
  { name: "Perkins-Tryon", class: "4A" },
  { name: "Plainview", class: "4A" },
  { name: "Poteau", class: "4A" },
  { name: "Purcell", class: "4A" },
  { name: "Sallisaw", class: "4A" },
  { name: "Seminole", class: "4A" },
  { name: "Skiatook", class: "4A" },
  { name: "Stigler", class: "4A" },
  { name: "Stilwell", class: "4A" },
  { name: "Sulphur", class: "4A" },
  { name: "Tecumseh", class: "4A" },
  { name: "Tuttle", class: "4A" },
  { name: "Verdigris", class: "4A" },
  { name: "Vinita", class: "4A" },
  { name: "Wagoner", class: "4A" },
  { name: "Weatherford", class: "4A" },
  { name: "Woodward", class: "4A" },

  # 3A Schools
  { name: "Adair", class: "3A" },
  { name: "Alva", class: "3A" },
  { name: "Antlers", class: "3A" },
  { name: "Atoka", class: "3A" },
  { name: "Beggs", class: "3A" },
  { name: "Bethel", class: "3A" },
  { name: "Blackwell", class: "3A" },
  { name: "Calera", class: "3A" },
  { name: "Caney Valley", class: "3A" },
  { name: "Casady", class: "3A" },
  { name: "Cascia Hall", class: "3A" },
  { name: "Cashion", class: "3A" },
  { name: "Central (Sallisaw)", class: "3A" },
  { name: "Central (Tulsa)", class: "3A" },
  { name: "Chandler", class: "3A" },
  { name: "Chelsea", class: "3A" },
  { name: "Chisholm", class: "3A" },
  { name: "Chouteau-Mazie", class: "3A" },
  { name: "Christian Heritage", class: "3A" },
  { name: "Coalgate", class: "3A" },
  { name: "Colbert", class: "3A" },
  { name: "Colcord", class: "3A" },
  { name: "Comanche", class: "3A" },
  { name: "Commerce", class: "3A" },
  { name: "Community Christian", class: "3A" },
  { name: "Cordell", class: "3A" },
  { name: "Crescent", class: "3A" },
  { name: "Crooked Oak", class: "3A" },
  { name: "Crossings Christian", class: "3A" },
  { name: "Dale", class: "3A" },
  { name: "Daniel Webster", class: "3A" },
  { name: "Davis", class: "3A" },
  { name: "Dewey", class: "3A" },
  { name: "Dibble", class: "3A" },
  { name: "Dickson", class: "3A" },
  { name: "Dove Science (Tulsa)", class: "3A" },
  { name: "Elmore City-Pernell", class: "3A" },
  { name: "Fairland", class: "3A" },
  { name: "Fairview", class: "3A" },
  { name: "Frederick", class: "3A" },
  { name: "Hartshorne", class: "3A" },
  { name: "Haskell", class: "3A" },
  { name: "Heavener", class: "3A" },
  { name: "Hennessey", class: "3A" },
  { name: "Henryetta", class: "3A" },
  { name: "Heritage Hall", class: "3A" },
  { name: "Hinton", class: "3A" },
  { name: "Hobart", class: "3A" },
  { name: "Holdenville", class: "3A" },
  { name: "Holland Hall", class: "3A" },
  { name: "Hooker", class: "3A" },
  { name: "Howe", class: "3A" },
  { name: "Hugo", class: "3A" },
  { name: "Hulbert", class: "3A" },
  { name: "Jones", class: "3A" },
  { name: "Kansas", class: "3A" },
  { name: "Kellyville", class: "3A" },
  { name: "Ketchum", class: "3A" },
  { name: "Keys (Parkhill)", class: "3A" },
  { name: "Kiefer", class: "3A" },
  { name: "Kingston", class: "3A" },
  { name: "Kipp Tulsa", class: "3A" },
  { name: "Konawa", class: "3A" },
  { name: "Latta", class: "3A" },
  { name: "Lexington", class: "3A" },
  { name: "Lincoln Christian", class: "3A" },
  { name: "Lindsay", class: "3A" },
  { name: "Little Axe", class: "3A" },
  { name: "Luther", class: "3A" },
  { name: "Mangum", class: "3A" },
  { name: "Marietta", class: "3A" },
  { name: "Marlow", class: "3A" },
  { name: "Meeker", class: "3A" },
  { name: "Merritt", class: "3A" },
  { name: "Metro Christian", class: "3A" },
  { name: "Millwood", class: "3A" },
  { name: "Minco", class: "3A" },
  { name: "Morris", class: "3A" },
  { name: "Morrison", class: "3A" },
  { name: "Mounds", class: "3A" },
  { name: "Newkirk", class: "3A" },
  { name: "Nowata", class: "3A" },
  { name: "OK Christian School", class: "3A" },
  { name: "Okemah", class: "3A" },
  { name: "Oklahoma Union", class: "3A" },
  { name: "Okmulgee", class: "3A" },
  { name: "Oktaha", class: "3A" },
  { name: "Panama", class: "3A" },
  { name: "Pathways", class: "3A" },
  { name: "Pawhuska", class: "3A" },
  { name: "Pawnee", class: "3A" },
  { name: "Perry", class: "3A" },
  { name: "Pocola", class: "3A" },
  { name: "Prague", class: "3A" },
  { name: "Preston", class: "3A" },
  { name: "Quapaw", class: "3A" },
  { name: "Rejoice Christian", class: "3A" },
  { name: "Riverside", class: "3A" },
  { name: "Roland", class: "3A" },
  { name: "Salina", class: "3A" },
  { name: "Sayre", class: "3A" },
  { name: "Sequoyah (Claremore)", class: "3A" },
  { name: "Sequoyah (Tahlequah)", class: "3A" },
  { name: "Silo", class: "3A" },
  { name: "Sperry", class: "3A" },
  { name: "Spiro", class: "3A" },
  { name: "Star-Spencer", class: "3A" },
  { name: "Stratford", class: "3A" },
  { name: "Stroud", class: "3A" },
  { name: "Talihina", class: "3A" },
  { name: "Tishomingo", class: "3A" },
  { name: "Tonkawa", class: "3A" },
  { name: "TSAS", class: "3A" },
  { name: "Tushka", class: "3A" },
  { name: "Valliant", class: "3A" },
  { name: "Vanoss", class: "3A" },
  { name: "Vian", class: "3A" },
  { name: "Victory Christian", class: "3A" },
  { name: "Walters", class: "3A" },
  { name: "Warner", class: "3A" },
  { name: "Washington", class: "3A" },
  { name: "Watonga", class: "3A" },
  { name: "Westville", class: "3A" },
  { name: "Wewoka", class: "3A" },
  { name: "Wilburton", class: "3A" },
  { name: "Wilson", class: "3A" },
  { name: "Wyandotte", class: "3A" },
  { name: "Wynnewood", class: "3A" },

  # 2A Schools
  { name: "Achille", class: "2A" },
  { name: "Afton", class: "2A" },
  { name: "Agra", class: "2A" },
  { name: "Alex", class: "2A" },
  { name: "Aline-Cleo", class: "2A" },
  { name: "Allen", class: "2A" },
  { name: "Amber-Pocasset", class: "2A" },
  { name: "Apache", class: "2A" },
  { name: "Arapaho-Butler", class: "2A" },
  { name: "Arkoma", class: "2A" },
  { name: "Arnett", class: "2A" },
  { name: "Asher", class: "2A" },
  { name: "Balko", class: "2A" },
  { name: "Barnsdall", class: "2A" },
  { name: "Battiest", class: "2A" },
  { name: "Beaver", class: "2A" },
  { name: "Bennington", class: "2A" },
  { name: "Big Pasture", class: "2A" },
  { name: "Billings", class: "2A" },
  { name: "Binger-Oney", class: "2A" },
  { name: "Blair", class: "2A" },
  { name: "Bluejacket", class: "2A" },
  { name: "Boise City", class: "2A" },
  { name: "Bokoshe", class: "2A" },
  { name: "Boswell", class: "2A" },
  { name: "Bowlegs", class: "2A" },
  { name: "Braggs", class: "2A" },
  { name: "Bray-Doyle", class: "2A" },
  { name: "Buffalo", class: "2A" },
  { name: "Buffalo Valley", class: "2A" },
  { name: "Burlington", class: "2A" },
  { name: "Burns Flat-Dill City", class: "2A" },
  { name: "Butner", class: "2A" },
  { name: "Caddo", class: "2A" },
  { name: "Calumet", class: "2A" },
  { name: "Calvin", class: "2A" },
  { name: "Cameron", class: "2A" },
  { name: "Canadian", class: "2A" },
  { name: "Caney", class: "2A" },
  { name: "Canton", class: "2A" },
  { name: "Canute", class: "2A" },
  { name: "Carnegie", class: "2A" },
  { name: "Carney", class: "2A" },
  { name: "Cave Springs", class: "2A" },
  { name: "Cement", class: "2A" },
  { name: "Central High", class: "2A" },
  { name: "Chattanooga", class: "2A" },
  { name: "Cherokee", class: "2A" },
  { name: "Cheyenne", class: "2A" },
  { name: "Cimarron", class: "2A" },
  { name: "Clayton", class: "2A" },
  { name: "Coleman", class: "2A" },
  { name: "Copan", class: "2A" },
  { name: "Corn Bible Academy", class: "2A" },
  { name: "Covington-Douglas", class: "2A" },
  { name: "Coyle", class: "2A" },
  { name: "Crowder", class: "2A" },
  { name: "Cyril", class: "2A" },
  { name: "Davenport", class: "2A" },
  { name: "Deer Creek-Lamont", class: "2A" },
  { name: "Depew", class: "2A" },
  { name: "Dewar", class: "2A" },
  { name: "Dover", class: "2A" },
  { name: "Drummond", class: "2A" },
  { name: "Drumright", class: "2A" },
  { name: "Duke", class: "2A" },
  { name: "Eagletown", class: "2A" },
  { name: "Earlsboro", class: "2A" },
  { name: "Empire", class: "2A" },
  { name: "Erick", class: "2A" },
  { name: "Fargo-Gage", class: "2A" },
  { name: "Felt", class: "2A" },
  { name: "Fletcher", class: "2A" },
  { name: "Forgan", class: "2A" },
  { name: "Fort Cobb-Broxton", class: "2A" },
  { name: "Fox", class: "2A" },
  { name: "Foyil", class: "2A" },
  { name: "Freedom", class: "2A" },
  { name: "Frontier", class: "2A" },
  { name: "Gans", class: "2A" },
  { name: "Garber", class: "2A" },
  { name: "Geary", class: "2A" },
  { name: "Geronimo", class: "2A" },
  { name: "Glencoe", class: "2A" },
  { name: "Goodwell", class: "2A" },
  { name: "Gore", class: "2A" },
  { name: "Gracemont", class: "2A" },
  { name: "Graham-Dustin", class: "2A" },
  { name: "Grandfield", class: "2A" },
  { name: "Granite", class: "2A" },
  { name: "Haileyville", class: "2A" },
  { name: "Hammon", class: "2A" },
  { name: "Hanna", class: "2A" },
  { name: "Hardesty", class: "2A" },
  { name: "Haworth", class: "2A" },
  { name: "Healdton", class: "2A" },
  { name: "Hillsdale Christian", class: "2A" },
  { name: "Hollis", class: "2A" },
  { name: "Hominy", class: "2A" },
  { name: "Hydro-Eakly", class: "2A" },
  { name: "Indiahoma", class: "2A" },
  { name: "Indianola", class: "2A" },
  { name: "Keota", class: "2A" },
  { name: "Kinta", class: "2A" },
  { name: "Kiowa", class: "2A" },
  { name: "Kremlin-Hillsdale", class: "2A" },
  { name: "Laverne", class: "2A" },
  { name: "Lawton Academy AS", class: "2A" },
  { name: "Leedey", class: "2A" },
  { name: "LeFlore", class: "2A" },
  { name: "Legacy Christian School", class: "2A" },
  { name: "Liberty", class: "2A" },
  { name: "Lomega", class: "2A" },
  { name: "Lone Wolf", class: "2A" },
  { name: "Lookeba-Sickles", class: "2A" },
  { name: "Macomb", class: "2A" },
  { name: "Mason", class: "2A" },
  { name: "Maud", class: "2A" },
  { name: "Maysville", class: "2A" },
  { name: "McCurtain", class: "2A" },
  { name: "Medford", class: "2A" },
  { name: "Midway", class: "2A" },
  { name: "Milburn", class: "2A" },
  { name: "Mill Creek", class: "2A" },
  { name: "Mooreland", class: "2A" },
  { name: "Moss", class: "2A" },
  { name: "Moyers", class: "2A" },
  { name: "Mt. View-Gotebo", class: "2A" },
  { name: "Mulhall-Orlando", class: "2A" },
  { name: "Navajo", class: "2A" },
  { name: "New Lima", class: "2A" },
  { name: "Ninnekah", class: "2A" },
  { name: "Oaks", class: "2A" },
  { name: "Oilton", class: "2A" },
  { name: "OK Christian Academy", class: "2A" },
  { name: "OK School Blind", class: "2A" },
  { name: "OK School for Deaf", class: "2A" },
  { name: "Okarche", class: "2A" },
  { name: "Okay", class: "2A" },
  { name: "Okeene", class: "2A" },
  { name: "Oklahoma Bible", class: "2A" },
  { name: "Olive", class: "2A" },
  { name: "Olustee-Eldorado", class: "2A" },
  { name: "Paden", class: "2A" },
  { name: "Paoli", class: "2A" },
  { name: "Pioneer-Pleasant Vale", class: "2A" },
  { name: "Pittsburg", class: "2A" },
  { name: "Pond Creek-Hunter", class: "2A" },
  { name: "Porter Consolidated", class: "2A" },
  { name: "Porum", class: "2A" },
  { name: "Prue", class: "2A" },
  { name: "Quinton", class: "2A" },
  { name: "Rattan", class: "2A" },
  { name: "Red Oak", class: "2A" },
  { name: "Regent Prep", class: "2A" },
  { name: "Reydon", class: "2A" },
  { name: "Ringling", class: "2A" },
  { name: "Ringwood", class: "2A" },
  { name: "Ripley", class: "2A" },
  { name: "Riverfield Country Day", class: "2A" },
  { name: "Rock Creek", class: "2A" },
  { name: "Roff", class: "2A" },
  { name: "Rush Springs", class: "2A" },
  { name: "Ryan", class: "2A" },
  { name: "Sasakwa", class: "2A" },
  { name: "Savanna", class: "2A" },
  { name: "Schulter", class: "2A" },
  { name: "Seiling", class: "2A" },
  { name: "Sentinel", class: "2A" },
  { name: "Sharon-Mutual", class: "2A" },
  { name: "Shattuck", class: "2A" },
  { name: "Shidler", class: "2A" },
  { name: "Smithville", class: "2A" },
  { name: "Snyder", class: "2A" },
  { name: "Soper", class: "2A" },
  { name: "South Coffeyville", class: "2A" },
  { name: "Southwest Covenant", class: "2A" },
  { name: "Springer", class: "2A" },
  { name: "Sterling", class: "2A" },
  { name: "Stonewall", class: "2A" },
  { name: "Stringtown", class: "2A" },
  { name: "Strother", class: "2A" },
  { name: "Stuart", class: "2A" },
  { name: "Summit Christian", class: "2A" },
  { name: "Sweetwater", class: "2A" },
  { name: "Taloga", class: "2A" },
  { name: "Temple", class: "2A" },
  { name: "Texhoma", class: "2A" },
  { name: "Thackerville", class: "2A" },
  { name: "The Academy", class: "2A" },
  { name: "Thomas-Fay-Custer", class: "2A" },
  { name: "Timberlake", class: "2A" },
  { name: "Tipton", class: "2A" },
  { name: "Tupelo", class: "2A" },
  { name: "Turner", class: "2A" },
  { name: "Turpin", class: "2A" },
  { name: "Tyrone", class: "2A" },
  { name: "Union City", class: "2A" },
  { name: "Varnum", class: "2A" },
  { name: "Velma-Alma", class: "2A" },
  { name: "Verden", class: "2A" },
  { name: "Vici", class: "2A" },
  { name: "Wanette", class: "2A" },
  { name: "Wapanucka", class: "2A" },
  { name: "Watts", class: "2A" },
  { name: "Waukomis", class: "2A" },
  { name: "Waurika", class: "2A" },
  { name: "Wayne", class: "2A" },
  { name: "Waynoka", class: "2A" },
  { name: "Webbers Falls", class: "2A" },
  { name: "Welch", class: "2A" },
  { name: "Weleetka", class: "2A" },
  { name: "Wellston", class: "2A" },
  { name: "Wesleyan Christian", class: "2A" },
  { name: "Wetumka", class: "2A" },
  { name: "Whitesboro", class: "2A" },
  { name: "Wilson (Henryetta)", class: "2A" },
  { name: "Wister", class: "2A" },
  { name: "Woodland", class: "2A" },
  { name: "Wright City", class: "2A" },
  { name: "Wynona", class: "2A" },
  { name: "Yale", class: "2A" },
  { name: "Yarbrough", class: "2A" }
]

# Create schools
created_count = 0
updated_count = 0
skipped_count = 0

ossaa_schools_data.each_with_index do |school_data, index|
  school_class = school_classes[school_data[:class]]

  begin
    school = School.find_or_initialize_by(
      name: school_data[:name],
      account: ossaa_account
    )

    if school.new_record?
      school.school_class = school_class
      school.save!
      created_count += 1
      print "+" if (index + 1) % 25 == 0
    else
      if school.school_class != school_class
        school.update!(school_class: school_class)
        updated_count += 1
        print "u" if (index + 1) % 25 == 0
      else
        skipped_count += 1
        print "." if (index + 1) % 25 == 0
      end
    end
  rescue => e
    puts "\n❌ Error creating #{school_data[:name]}: #{e.message}"
    next
  end
end

puts "\n\n🎉 OSSAA Schools seeding completed!"
puts "   📊 Summary:"
puts "   - Account: #{ossaa_account.name} ✓"
puts "   - School Classes: #{school_classes.count} ✓"
puts "   - Schools Created: #{created_count}"
puts "   - Schools Updated: #{updated_count}"
puts "   - Schools Skipped (already current): #{skipped_count}"
puts "   - Total Schools Processed: #{ossaa_schools_data.count}"
puts "\n   📈 Progress Legend:"
puts "   + = Created, u = Updated, . = Skipped (every 25 schools)"

# Verification
puts "\n   🔍 Verification:"
actual_school_count = School.joins(:account).where(accounts: { name: "OSSAA" }).count
actual_class_count = SchoolClass.joins(:account).where(accounts: { name: "OSSAA" }).count
puts "   - Schools in database: #{actual_school_count}"
puts "   - School classes in database: #{actual_class_count}"

if actual_school_count == ossaa_schools_data.count && actual_class_count == 5
  puts "   ✅ Verification passed!"
else
  puts "   ⚠️  Verification mismatch - please check for errors above"
end

puts "   🏆 All OSSAA schools are now in your database!"
